image: gitpod/workspace-full

tasks:
  - init: npm install --prefix frontend
    command: npm start --prefix frontend

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
